import { CheckCircle2, Circle, LoaderCircle } from 'lucide-react'
import { useAuthStore } from '@/store/auth-store'
import { useContextStore } from '@/store/context-store'
import { useApiQuery } from '@/hooks/use-api-query'
import { workflowService } from '@/services/workflow-service'
import { Card } from './ui'
import { AnalysisCenter } from './analysis-center'

export function WorkflowStatus() { const { user } = useAuthStore(); const { selectedCourseId, semester, selectedCurriculumId, selectedLectureId } = useContextStore(); const status = useApiQuery(['analysis-status', selectedLectureId], () => workflowService.status(selectedLectureId!), Boolean(selectedLectureId), { retry: false }); const data = status.data; const rows = [{ label: 'Authenticated', ready: Boolean(user) }, { label: 'Course selected', ready: Boolean(selectedCourseId) }, { label: 'Semester selected', ready: Boolean(semester) }, { label: 'Curriculum uploaded', ready: Boolean(selectedCurriculumId) }, { label: 'Validation complete', ready: data?.validation_status === 'COMPLETED' }, { label: 'Coverage complete', ready: data?.coverage_status === 'COMPLETED' }, { label: 'Teaching complete', ready: data?.teaching_status === 'COMPLETED' }, { label: 'Recommendations complete', ready: data?.recommendation_status === 'COMPLETED' }, { label: 'Explainability complete', ready: data?.explainability_status === 'COMPLETED' }]; return <><Card><h2 className="font-semibold">Workflow status</h2><p className="mt-1 text-sm text-muted">{data?.overall_status === 'PROCESSING' ? `${data.current_stage.replace('_', ' ')} — ${data.progress_percentage}%` : 'Your academic intelligence pipeline at a glance.'}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{rows.map((row) => <div key={row.label} className="flex items-center gap-2 rounded-xl bg-elevated px-3 py-2 text-sm">{status.isLoading && row.label.includes('complete') ? <LoaderCircle className="animate-spin text-muted" size={16}/> : row.ready ? <CheckCircle2 className="text-success" size={16}/> : <Circle className="text-muted" size={16}/>}<span className={row.ready ? 'text-ink' : 'text-muted'}>{row.label}</span></div>)}</div></Card><AnalysisCenter/></> }
