import { Search, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { useMemo, useState } from 'react'
import { useUiStore } from '@/store/ui-store'

const searchable = ['Dashboard', 'Curriculum', 'Lectures', 'Coverage', 'Technical Validation', 'Teaching Intelligence', 'Recommendations', 'Explainable AI', 'Analytics', 'Reports', 'Settings']
export function GlobalSearch() { const { searchOpen, setSearchOpen } = useUiStore(); const [query, setQuery] = useState(''); const results = useMemo(() => searchable.filter((item) => item.toLowerCase().includes(query.toLowerCase())), [query]); return <AnimatePresence>{searchOpen && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[60] grid place-items-start bg-slate-950/30 p-4 pt-[12vh]" role="dialog" aria-modal="true" aria-label="Global search"><div className="absolute inset-0" onClick={() => setSearchOpen(false)}/><motion.div initial={{ y: -12, scale: .98 }} animate={{ y: 0, scale: 1 }} className="surface relative w-full max-w-xl overflow-hidden"><div className="flex items-center gap-3 border-b border-line p-4"><Search size={19} className="text-muted"/><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search lectures, topics, insights…" className="w-full bg-transparent text-sm outline-none placeholder:text-muted"/><button className="icon-button h-8 w-8" onClick={() => setSearchOpen(false)} aria-label="Close search"><X size={17}/></button></div><div className="p-2">{results.length ? results.map((item) => <button key={item} className="flex w-full rounded-xl px-3 py-3 text-left text-sm hover:bg-elevated" onClick={() => setSearchOpen(false)}>{item}</button>) : <p className="p-5 text-center text-sm text-muted">No matches found.</p>}</div></motion.div></motion.div>}</AnimatePresence> }

export function NotificationPanel() { const { notificationsOpen, setNotificationsOpen, notifications, markAllRead } = useUiStore(); return <AnimatePresence>{notificationsOpen && <><motion.button initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} aria-label="Close notifications" onClick={() => setNotificationsOpen(false)} className="fixed inset-0 z-40 bg-slate-950/20"/><motion.aside initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', damping: 28, stiffness: 280 }} className="fixed inset-y-0 right-0 z-50 w-full max-w-md border-l border-line bg-surface p-5 shadow-float" aria-label="Notifications"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Notifications</h2><p className="text-xs text-muted">Updates from your workspace</p></div><button onClick={markAllRead} className="text-sm font-medium text-brand">Mark all read</button></div><div className="mt-6 space-y-2">{notifications.map((note) => <article key={note.id} className="rounded-xl border border-line p-4"><div className="flex items-start gap-3"><i className={`mt-1.5 h-2 w-2 rounded-full ${note.priority === 'danger' ? 'bg-danger' : note.priority === 'warning' ? 'bg-warning' : 'bg-info'}`}/><div><h3 className="text-sm font-semibold">{note.title}</h3><p className="mt-1 text-sm text-muted">{note.body}</p><span className="mt-2 block text-xs text-muted">{note.category} · just now</span></div></div></article>)}</div></motion.aside></>}</AnimatePresence> }
