"""Add mime_type to curricula and reference_materials

Revision ID: 1200dbbbdae5
Revises: c4e8a7b2d9f1
Create Date: 2026-08-02 17:42:04.951341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1200dbbbdae5'
down_revision: Union[str, Sequence[str], None] = 'c4e8a7b2d9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('mime_type', sa.String(length=255), nullable=False))
    op.add_column('reference_materials', sa.Column('academic_term_id', sa.Uuid(), nullable=False))
    op.add_column('reference_materials', sa.Column('mime_type', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'reference_materials', 'academic_terms', ['academic_term_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_materials', type_='foreignkey')
    op.drop_column('reference_materials', 'mime_type')
    op.drop_column('reference_materials', 'academic_term_id')
    op.drop_column('curricula', 'mime_type')
    # ### end Alembic commands ###
