"""Initial Schema

Revision ID: de90817c6e44
Revises: 
Create Date: 2026-08-01 22:09:20.534697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de90817c6e44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_course_code_key'), 'courses', type_='unique')
    op.drop_index(op.f('idx_courses_code'), table_name='courses')
    op.drop_index(op.f('idx_courses_department'), table_name='courses')
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.drop_index(op.f('idx_curricula_course'), table_name='curricula')
    op.drop_constraint(op.f('faculty_employee_id_key'), 'faculty', type_='unique')
    op.drop_index(op.f('idx_faculty_department'), table_name='faculty')
    op.drop_index(op.f('idx_faculty_employee_id'), table_name='faculty')
    op.create_index(op.f('ix_faculty_employee_id'), 'faculty', ['employee_id'], unique=True)
    op.drop_index(op.f('idx_lecture_sessions_course'), table_name='lecture_sessions')
    op.drop_index(op.f('idx_lecture_sessions_date'), table_name='lecture_sessions')
    op.drop_index(op.f('idx_lecture_sessions_faculty'), table_name='lecture_sessions')
    op.drop_index(op.f('idx_recommendations_session'), table_name='recommendations')
    op.drop_index(op.f('idx_reports_faculty'), table_name='reports')
    op.drop_index(op.f('idx_reports_session'), table_name='reports')
    op.alter_column('topics', 'expected_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_topics_curriculum'), table_name='topics')
    op.drop_index(op.f('idx_topics_parent'), table_name='topics')
    op.drop_index(op.f('idx_transcript_segments_topic'), table_name='transcript_segments')
    op.drop_index(op.f('idx_transcript_segments_transcript'), table_name='transcript_segments')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('idx_validation_flags_ref_material'), table_name='validation_flags')
    op.drop_index(op.f('idx_validation_flags_segment'), table_name='validation_flags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_validation_flags_segment'), 'validation_flags', ['segment_id'], unique=False)
    op.create_index(op.f('idx_validation_flags_ref_material'), 'validation_flags', ['reference_material_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_transcript_segments_transcript'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_index(op.f('idx_transcript_segments_topic'), 'transcript_segments', ['topic_id'], unique=False)
    op.create_index(op.f('idx_topics_parent'), 'topics', ['parent_topic_id'], unique=False)
    op.create_index(op.f('idx_topics_curriculum'), 'topics', ['curriculum_id'], unique=False)
    op.alter_column('topics', 'expected_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('idx_reports_session'), 'reports', ['session_id'], unique=False)
    op.create_index(op.f('idx_reports_faculty'), 'reports', ['faculty_id'], unique=False)
    op.create_index(op.f('idx_recommendations_session'), 'recommendations', ['session_id'], unique=False)
    op.create_index(op.f('idx_lecture_sessions_faculty'), 'lecture_sessions', ['faculty_id'], unique=False)
    op.create_index(op.f('idx_lecture_sessions_date'), 'lecture_sessions', ['lecture_date'], unique=False)
    op.create_index(op.f('idx_lecture_sessions_course'), 'lecture_sessions', ['course_id'], unique=False)
    op.drop_index(op.f('ix_faculty_employee_id'), table_name='faculty')
    op.create_index(op.f('idx_faculty_employee_id'), 'faculty', ['employee_id'], unique=False)
    op.create_index(op.f('idx_faculty_department'), 'faculty', ['department_id'], unique=False)
    op.create_unique_constraint(op.f('faculty_employee_id_key'), 'faculty', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_curricula_course'), 'curricula', ['course_id'], unique=False)
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.create_index(op.f('idx_courses_department'), 'courses', ['department_id'], unique=False)
    op.create_index(op.f('idx_courses_code'), 'courses', ['course_code'], unique=False)
    op.create_unique_constraint(op.f('courses_course_code_key'), 'courses', ['course_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
